#!/bin/bash

set -ex

fonts=(
  BitstreamVeraSansMono
  CascadiaCode
  CodeNewRoman
  DroidSansMono
  FiraCode
  FiraMono
  Go-Mono
  Hack
  Hermit
  JetBrainsMono
  Meslo
  Noto
  Overpass
  ProggyClean
  RobotoMono
  SourceCodePro
  SpaceMono
  Ubuntu
  UbuntuMono
)

latest_json=$(curl -fsS https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest)
version=$(jq -r .name <<<"$latest_json")
if [[ -z "$version" || "$version" == "null" ]]; then
  version="v3.2.1"
fi
echo "latest version: $version"

fonts_dir="${HOME}/.local/share/fonts"
#fonts_dir="/usr/share/fonts"

if [[ ! -d "$fonts_dir" ]]; then
  mkdir -p "$fonts_dir"
fi

for font in "${fonts[@]}"; do
  zip_file="${font}.zip"
  if [[ ! -f "$zip_file" ]]; then
    download_url="https://github.com/ryanoasis/nerd-fonts/releases/download/${version}/${zip_file}"
    echo "Downloading $download_url"
    wget "$download_url" -O "$zip_file~"
    mv "$zip_file~" "$zip_file"
  fi
  unzip -o "$zip_file" -d "$fonts_dir"
done

find "$fonts_dir" -name 'Windows Compatible' -delete

fc-cache -fv

for font in "${fonts[@]}"; do
  zip_file="${font}.zip"
  rm -f "$zip_file"
done

# vim:set sw=2 ts=2 et:
