#!/bin/sh -ex

warn()
{
	echo "$CMD: $*" 1>&2
}

err()
{
	warn "$*"
	exit 1
}

usage()
{
	[ $# -eq 0 ] || warn "$*"
	echo "usage: $0 HOST" 1>&2
	exit 1
}

CMD="${0##*/}"

[ $# -eq 1 ] || usage "invalid number of arguments"

HOST="$1"

cd "`dirname "$0"`"

TMPDIR="`mktemp -d /tmp/$CMD.$$.XXXXXX`"
[ $? -eq 0 ] || err "could not create temporary directory"
trap 'rm -fr "$TMPDIR"' 0

WORKDIR="$TMPDIR/work"
mkdir -p "$WORKDIR" || err "error creating temporary work directory"

PKGFILE="$TMPDIR/dotfiles.tar"
touch "$PKGFILE" || err "error creating temporary dotfiles package"

for f in dot.*; do
	g=".${f#dot.}"
	cp -p "$f" "$WORKDIR/$g" || err "error copying dotfile"
	tar -rf "$PKGFILE" -C "$WORKDIR" "$g" || err "error packaging dotfile"
done

gzip -9 "$PKGFILE" || err "error compressing dotfiles package"

ssh "$HOST" tar -xzf - < "$PKGFILE.gz" || err "error uploading dotfiles"
