#!/bin/sh -e

warn()
{
	echo "$CMD: $*" 1>&2
}

err()
{
	warn "$*"
	exit 1
}

usage()
{
	[ $# -eq 0 ] || warn "$*"
	echo "usage: $0 [-r REMOTEHOST] [-d DESTDIR]" 1>&2
	exit 1
}

CMD="${0##*/}"

PARSED=`getopt -o 'd:r:' -- "$@"`
[ $? -eq 0 ] || usage

eval set -- "$PARSED"

DESTDIR=""
REMOTEHOST=""

while [ $# -gt 0 ]; do
	case "$1" in
	-d) DESTDIR="$2"; shift 2 ;;
	-r) REMOTEHOST="$2"; shift 2 ;;
	--) shift 1; break ;;
	*) usage "internal error at $LINENO" ;;
	esac
done

[ $# -eq 0 ] || usage "excess arguments ($#:$*)"

if [ "$REMOTEHOST" = "" ]; then
	if [ "$DESTDIR" = "" ]; then
		usage "you must specify the \`-r' and/or \`-d' arguments"
	fi

	if [ ! -d "$DESTDIR" ]; then
		err "path \`$DESTDIR' is not a valid directory"
	fi
else
	if [ "$DESTDIR" = "" ]; then
		DESTDIR="."
	fi
fi

cd "`dirname "$0"`"

TMPDIR="`mktemp -d /tmp/$CMD.$$.XXXXXX`"
[ $? -eq 0 ] || err "could not create temporary directory"
trap 'rm -fr "$TMPDIR"' 0

WORKDIR="$TMPDIR/work"
mkdir -p "$WORKDIR" || err "error creating temporary work directory"

PKGFILE="$TMPDIR/dotfiles.tar"
touch "$PKGFILE" || err "error creating temporary dotfiles package"

for f in dot.*; do
	g=".${f#dot.}"
	cp -p "$f" "$WORKDIR/$g" || err "error copying dotfile"
	tar -rf "$PKGFILE" -C "$WORKDIR" "$g" || err "error packaging dotfile"
done

if [ "$REMOTEHOST" = "" ]; then
	tar -xf "$PKGFILE" -C "$DESTDIR" || err "error uploading dotfiles"
else
	gzip "$PKGFILE" || err "error compressing dotfiles package"
	ssh "$REMOTEHOST" "tar -xzf - -C '$DESTDIR'" < "$PKGFILE.gz" || err "error uploading dotfiles"
fi
