#!/bin/sh -e

warn()
{
	echo "$CMD: $*" 1>&2
}

err()
{
	warn "$*"
	exit 1
}

usage()
{
	[ $# -eq 0 ] || warn "$*"
	echo "usage: $0 [-r REMOTEHOST] [-d DESTDIR]" 1>&2
	exit 1
}

CMD="${0##*/}"

DESTDIR=""
REMOTEHOST=""

while [ $# -gt 0 ]; do
	case "$1" in
	-d) DESTDIR="$2"; shift 2 ;;
	-r) REMOTEHOST="$2"; shift 2 ;;
	*) break ;;
	esac
done

[ $# -eq 0 ] || usage "excess arguments ($#:$*)"

if [ "$REMOTEHOST" = "" ]; then
	if [ "$DESTDIR" = "" ]; then
		usage "you must specify the \`-r' and/or \`-d' arguments"
	fi

	if [ ! -d "$DESTDIR" ]; then
		err "path \`$DESTDIR' is not a valid directory"
	fi
else
	if [ "$DESTDIR" = "" ]; then
		DESTDIR="."
	fi
fi

cd "`dirname "$0"`"

if which mktemp > /dev/null; then
	TMPDIR="`mktemp -d /tmp/$CMD.$$.XXXXXX`"
else
	TMPDIR="/tmp/$CMD.$$.XXXXXX"
	mkdir "$TMPDIR"
fi

[ $? -eq 0 ] || err "could not create temporary directory"
trap 'rm -fr "$TMPDIR"' 0

WORKDIR="$TMPDIR/work"
mkdir -p "$WORKDIR" || err "error creating temporary work directory"

PKGFILE="$TMPDIR/dotfiles.tar"

tarcmd="c"
for f in dot.*; do
	g=".${f#dot.}"
	cp -p "$f" "$WORKDIR/$g" || err "error copying dotfile"
	tar -${tarcmd}f "$PKGFILE" -C "$WORKDIR" "$g" || err "error packaging dotfile"
	if [ $tarcmd = c ]; then
		tarcmd="r"
	fi
done

for f in bin/*; do
	tar -${tarcmd}f "$PKGFILE" "$f" || err "error packaging dotfile"
	if [ $tarcmd = c ]; then
		tarcmd="r"
	fi
done

if [ "$REMOTEHOST" = "" ]; then
	tar -xf "$PKGFILE" -C "$DESTDIR" || err "error uploading dotfiles"
else
	gzip "$PKGFILE" || err "error compressing dotfiles package"
	# Add `--no-same-owner' when using GNU tar?
	ssh "$REMOTEHOST" "tar -m -xzf - -C '$DESTDIR'" < "$PKGFILE.gz" || err "error uploading dotfiles"
fi
